TARGET_SYSTEM_PROP := device/phh/treble/system.prop $(TARGET_SYSTEM_PROP)
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/phh/treble/bluetooth
TARGET_EXFAT_DRIVER := exfat

# NFC
#BOARD_NFC_CHIPSET := pn544
#TARGET_NEEDS_PLATFORM_TEXT_RELOCATIONS := true
